// 
// File: Body.h
// 
// Date: 24.12.14 17:11
// 
// Generated by: Idatto, version 1.3
// 
// Description:


#ifndef body_
#define body_

#include <vector>
#include <string>



class Body
{
    public:
        // Reacts to insulin and returns “True” when done.
        // 
        // Parameter:
        // - amount_injected: the amount of insulin injected
        virtual bool reactToInsulin(float amount_injected);
        // Reacts to glucagon and returns “True” when done.
        // 
        // Parameter:
        // - amount: the amount of glucagon injected
        virtual bool reactToGlucagon(float amount);

    private:
        float BloodsugarLevel;
        // Increases the blood sugar level depending on the strength parameter. 
        // Returns “True” when done. 
        // 
        // Parameter:
        // - strength: The strength of raising the blood sugar level 1: calm 2: 
        //     middle 3: fast 
        virtual bool increaseBloodsugar(int strength);
        // Decreases the blood sugar level depending on the strength parameter. 
        // Returns “True” when done. 
        // 
        // Parameter:
        // - strength: The strength of sinking the blood sugar level 1: calm 2: 
        //     middle 3: fast 
        virtual bool decreaseBloodsugar(int strength);

};

#endif
