// 
// File: ControlSystem.cpp
// 
// Date: 24.12.14 17:11
// 
// Generated by: Idatto, version 1.3
// 
// Description:

#include "ControlSystem.h"



// Checks the operation hours of the mechanical parts (motor) and returns the 
// value in hours. 
int ControlSystem::checkOperationHours()
{
}

// Checks the scheduler for correct operation and returns “True” when 
// everything is working fine! 
bool ControlSystem::checkScheduler()
{
}

// Checks the hormone reservoir and returns “True” when everything is fine
bool ControlSystem::checkPump()
{
}

// Checks the tracer and returns “True” when everything is fine!
bool ControlSystem::checkTracer()
{
}

// checks the batteries charging state and returns the value in percent
int ControlSystem::checkBatteryStatus()
{
}




