// 
// File: HormoneReservoir.h
// 
// Date: 24.12.14 17:11
// 
// Generated by: Idatto, version 1.3
// 
// Description:


#ifndef hormonereservoir_
#define hormonereservoir_

#include <vector>
#include <string>



class HormoneReservoir
{
    private:
        // decreases glucagon level in reservoir when injected to body and 
        // returns “True” when done 
        virtual bool decreaseGlucagonLevel(float amount);

};

#endif
