// 
// File: HormoneReservoir.cpp
// 
// Date: 24.12.14 17:11
// 
// Generated by: Idatto, version 1.3
// 
// Description:

#include "HormoneReservoir.h"



// decreases glucagon level in reservoir when injected to body and returns 
// “True” when done 
bool HormoneReservoir::decreaseGlucagonLevel(float amount)
{
}




