// 
// File: Pump.h
// 
// Date: 24.12.14 17:11
// 
// Generated by: Idatto, version 1.3
// 
// Description: Measure Blood Sugar Level, Calculate Units of Hormone (Insulin or Glucagon) and Inject Calculated Units
//
// Authors: Jenny Kreger and Markus Ernst

#ifndef pump_
#define pump_

#include "Tracer.h"
#include <QObject>

using namespace std;



class Pump : public QObject
{
    Q_OBJECT

// ATTRIBUTES
private:
        /* When pump is active injecting insulin the value will be 1, when
        // injecting glucagon the value will be 2 and when inactive the value
        // will be 0.
        */
        int active;
        float insulinReservoirLevel;
        float glucagonReservoirLevel;

        // current level
        int currentBloodSugarLevel;

        // the blood sugar level in the latest cycle
        int latestBloodSugarLevel;

        // maximal healthy blood sugar level
        int maxBloodSugarLevel;

        // minimum healthy blood sugar level
        int minBloodSugarLevel;

        // target to decrease blood sugar level with insulin injection
        int upperTargetBloodSugarLevel;

        // target to increase blood sugar level with glucagon injection
        int lowerTargetBloodSugarLevel;

        // inject insulin or glucagon, true when insuling
        bool insulin;
        // true if there was an injection in the last cycle
        bool delay;

        // current battery power level
        int batteryPowerLevel;
        //for logging purposes
        Tracer tracer;

        // hormone sensitivity factor
        int hsf;

// END ATTRBUTES


// FUNCTIONS
public:
        /* "main"-function for pump
        // triggered by Scheduler.
        */
        virtual bool runPump();
        /*
         * Checks the battery status and returns the value in percent.
         */
        int checkPumpBatteryStatus(void);

private:
        /* Injects either insulin or glucagon into the body.
        //
        // Parameters:
        // - amount : int       the amount of FU that should be injected
        // - insulin : bool     true if the hormone to inject is insulin, false if it is glucagon
        */
        virtual bool injectHormone(int amount, bool insulin);

        /* Decreases either the insulin or the glucagon level in the reservoir when a hormone is
        // injected to the body
        //
        // Parameters:
        // - amount : int       the amount of FU by that the reservoir should be decreased
        // - insulin : bool     true if the hormone to inject is insulin, false if it is glucagon
        */
        virtual bool decreaseHormoneLevel(int amount, bool insulin);

 /*
 * author: Markus
 * BEGIN <<<<< meine bevorzugte loesung
 */
        /* Calculates the amount of hormone needed based on the blood sugar levels.
        // Returns fictional Units of specified hormone, see parameters.
        //
        // Parameter:
        // - targetBloodSugarLevel:     predefined value to raise or reduce blood sugar level to,
        //                              e.g. 90mg/dl -> targetBloodSugarLevel = 90;
        //
        // - currentBloodSugarLevel:    current value of BSL, e.g. 160mg/dl -> currentBloodSugarLevel = 160;
        //
        // - hsf:                       hormon sensitivity factor. Factor which indicates how much blood sugar
        //                              one unit of used hormone raises or reduces , e.g. 1:5 -> 1 unit hormone
        //                              raises/reduces 5mg/dl glucose -> hsf = 5;
        //
        // - hormone:                   what sort of hormone is used, e.g. insulin or glucagon.
        //
        // >> jenny's solution <<       strings as parameters are bad. really bad. so lets just use a bool
        //                              called insulin that is true when insulin should be injected and false in
        //                              case of glucagon.
        // - insulin:                   true when insulin should be injected, false when glucagon should be injected
        */
        virtual int calculateNeededHormone(int targetBloodSugarLevel);
        /*
         * recharges battery up to 100% of charge.
         *
         * Parameters:
         * - power: level of recharge energy.
         */
         void rechargeBatteryPower(int charge);

// END FUNCTIONS


// GETTER
public:
        /* Checks the entire pump (reservoir, mechanical parts) and returns
        // “True” when everything is working fine.
        */
        virtual bool getPumpStatus();
private:
        // Returns the insulin level in the reservoir.
        virtual int getInsulinReservoirLevel();
        // Returns the glucagon level in the reservoir.
        virtual int getGlucagonReservoirLevel();
        // Checks the blood sugar concentration and returns the value.
        virtual int getCurrentBloodSugarLevel();
        /* returns battery power level
        // In case of a critical status (level smaller than 15%) the user will
        // be notified acoustically and the incident will be logged by the
        // tracer.
        */
        virtual int getBatteryPowerLevel();

// END GETTER


// SETTER
        /*
         * sets power level. power is decreasing due to usage of pump. only decreases when pump is in use.
         *
         * Parameters:
         * - powerdrain: int    amount of power drained from battery.
         */
         void setBatteryPowerLevel(int powerdrain);

// END SETTER

         // SLOTS
public slots:
        /**
         * Refills the Insulin in the Reservoir of the Pump
         */
        void refillInsulin();
        /**
         * Refills the Glucagon in the Reservoir of the Pump
         */
        void refillGlucagon();

// END SLOTS


// SIGNALS

signals:
    /* Callback for updating Insulin Reservoir in the UI.
    //
    // Parameter:
    // - The current amount of insulin in the reservoir
    */
    void updateInsulinReservoir(float amount);
    /* Callback for updating Glucagon Reservoir in the UI.
    //
    // Parameter:
    // - The current amount of glucagon in the reservoir
    */
    void updateGlucagonReservoir(float amount);

// END SIGNALS
}; //END HEADER

#endif
