// 
// File: Scheduler.h
// 
// Date: 24.12.14 17:11
// 
// Generated by: Idatto, version 1.3
// 
// Description:


#ifndef scheduler_
#define scheduler_

#include <vector>
#include <string>
#include "Pump.h"



class Scheduler
{
    public:
        // answers ControlSystem’s call for checkScheduler()
        virtual void getStatus();

    private:
        int TimerResetValueSec;
        // Counts the operation hours and notices the user when an inspection 
        // is needed or when system lifetime (because of mechanical outwear) is 
        // reached. 
        float TotalOperationHours;
        // triggers the pump which then checks the blood sugar level
        virtual bool triggerPump();
        // resets the timer and sets the countdown time according to parameter
        virtual bool resetTimer(int time_min);
        // Starts the counter for operation hours and returns “True” when 
        // successfully started. The value will be written to 
        // “TotalOperationHours”. 
        // 
        virtual bool startOperationHoursCounter();
        // Stops the counter for operation hours and returns “True” when 
        // successfully stopped. The value will be written to 
        // “TotalOperationHours”. 
        // 
        virtual bool stopOperationHoursCounter();

};

#endif
