// 
// File: Scheduler.cpp
// 
// Date: 24.12.14 17:11
// 
// Generated by: Idatto, version 1.3
// 
// Description:

#include "Scheduler.h"



// triggers the pump which then checks the blood sugar level
bool Scheduler::triggerPump()
{
}

// resets the timer and sets the countdown time according to parameter
bool Scheduler::resetTimer(int time_min)
{
}

// answers ControlSystem’s call for checkScheduler()
void Scheduler::getStatus()
{
}

// Starts the counter for operation hours and returns “True” when successfully 
// started. The value will be written to “TotalOperationHours”. 
// 
bool Scheduler::startOperationHoursCounter()
{
}

// Stops the counter for operation hours and returns “True” when successfully 
// stopped. The value will be written to “TotalOperationHours”. 
// 
bool Scheduler::stopOperationHoursCounter()
{
}




