// 
// File: Scheduler.cpp
// 
// Date: 24.12.14 17:11
// 
// Generated by: Idatto, version 1.3
// 
// Description:  Triggering the hormone pump
//               Keep track of operation time
//
// Author:       Sven Sperner, sillyconn@gmail.com


#include "Scheduler.h"

using namespace std;



Scheduler::Scheduler()
{
    startOperationHoursCounter();
}

Scheduler::~Scheduler()
{
    stopOperationHoursCounter();
}

// triggers the pump which then checks the blood sugar level
bool Scheduler::triggerPump()
{
/*    if(!Pump.trigger()/run()/main())
    {
        return false;
    }
    else*/
    {
        return true;
    }
}

// resets the timer and sets the countdown time according to parameter
bool Scheduler::resetTimer(int time_min)
{
    TotalOperationTime = time_min;
    Timer.restart();

    return true;
}

// answers ControlSystem’s call for checkScheduler()
bool Scheduler::getStatus()
{
    return true;
}

// answers ControlSystem’s call for checkOperationTime()
qint64 Scheduler::getOperationTime()
{
    return TotalOperationTime;
}

// Starts the counter for operation hours and returns “True” when successfully
// started. The value will be written to “TotalOperationHours”. 
bool Scheduler::startOperationHoursCounter()
{
    Timer.start();

    SaveFile = new QSettings("InsulinPump.conf", QSettings::NativeFormat);
    SaveFile->beginGroup( "InsulinPump" );
    TotalOperationTime = SaveFile->value("TotalOperationTime").toLongLong();

    return true;
}

// Stops the counter for operation hours and returns “True” when successfully 
// stopped. The value will be written to “TotalOperationHours”.
bool Scheduler::stopOperationHoursCounter()
{
    TotalOperationTime += Timer.elapsed();

    SaveFile->beginGroup( "InsulinPump" );
    SaveFile->setValue("TotalOperationTime", TotalOperationTime);

    return true;
}




