// 
// File: Tracer.cpp
// 
// Date: 24.12.14 17:11
// 
// Generated by: Idatto, version 1.3
// 
// Description:

#include "Tracer.h"
#include <QString>
#include <iostream>

using namespace std;



Tracer::Tracer()
{
    filename = LOGFILE_NAME;
}

Tracer::Tracer(QString path)
{
    filename = path;
}

// Writes the message to the log file. Every Message is signed by date and time.
// When writing to file has finished, “True” is returned!
bool Tracer::writeStatusLog(QString message)
{
    // Update UI
    emit writeStatusLogInUi(message);
    return true;
}

// Writes the message to the log file. Every Message is signed by date and time.
// When writing to file has finished, “True” is returned!
bool Tracer::writeWarningLog(QString message)
{
    // Update UI
    emit writeWarningLogInUi(message);
    return true;
}

// Writes the message to the log file. Every Message is signed by date and time.
// When writing to file has finished, “True” is returned!
bool Tracer::writeCriticalLog(QString message)
{
    // Update UI
    emit writeCriticalLogInUi(message);
    return true;
}

// Plays an acoustic sound and returns “True” when done
bool Tracer::playAcousticWarning()
{
    cout << "ring-ring...";
    return true;
}

// vibrates on a specific event and returns “True” when done
bool Tracer::vibrationWarning()
{
    cout << "vibrating...";
    return true;
}

QString Tracer::getFilename()
{
    return filename;
}

void Tracer::setFilename(QString value)
{
    filename = value;
}





