// 
// File: Body.h
// 
// Date: 07.01.15 15:12
// 
// Generated by: Idatto, version 1.3
// 
// Description: Header file for body simulation


#ifndef body_
#define body_

#include <vector>
#include <string>

class Body
{
    public:
    // changes the blood sugar level;
    // increasing: if True: rising; if False: falling
    // strength: the factor the BSL is rising or falling
    virtual bool changeBloodSugarLevel(float strength, bool increasing, bool use_insulin_constant);
    virtual float getBloodSugarLevel();
    virtual void setBloodSugarLevel(float);
    
    Body(float BSL, int constant);
    ~Body();

    private:
    float BloodsugarLevel;
    int insulin_constant;

};

#endif
